AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true

Layout/EndOfLine:
  EnforcedStyle: lf

Metrics/ClassLength:
  Enabled: false

Metrics/LineLength:
  Enabled: true
  Max: 120

Metrics/MethodLength:
  Enabled: false

Style/Documentation: # TODO: enable this cop
  Enabled: false
