AllCops:
  TargetRubyVersion: 2.6
  DisplayCopNames: true
  DisplayStyleGuide: true

Gemspec/DateAssignment:
  Enabled: true

Layout/EmptyLines:
  Enabled: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/LineLength:
  Enabled: true
  Max: 120

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/AmbiguousOperatorPrecedence:
  Enabled: false

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/RequireRelativeSelfPath:
  Enabled: false

Lint/StructNewOverride:
  Enabled: true

Lint/SuppressedException:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Security/IoMethods:
  Enabled: true

Style/Documentation: # TODO: enable this cop
  Enabled: false

Style/ExponentialNotation:
  Enabled: true

Style/FormatStringToken:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/MapToHash:
  Enabled: true

Style/RedundantArgument:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true
